services:
  person-service:
    build: .
    ports:
      - "8000:8000"
    networks:
      - backend

  person-postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "123456"
    ports:
      - "5432:5432"
    networks:
      - backend

networks:
  backend: